# Generated by Django 4.2.6 on 2023-10-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bmi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='length_of_menses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_fertility_formula',
            field=models.IntegerField(default=0),
        ),
    ]
